server.port=4000
eureka.instance.preferIpAddress=true
eureka.instance.instance-id=${spring.cloud.client.ipAddress}:${server.port} 
eureka.client.serviceUrl.defaultZone=http://eureka-server.en-322.svc.cluster.local:4000/eureka


spring:
  application:
    name: spring-cloud-eureka
server:
  port: 4000
eureka:
  instance:
    hostname: localhost                                                 # 设置主机名
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
  client:

    healthcheck :
          enabled : true
    serviceUrl:
      #eureka-server.en-322.svc.cluster.local  服务名
      # eureka-server  StatefulSet名字
      # eureka-server  Service 名字
      # en-322     namespace
      #defaultZone: http://eureka-server-0.eureka-server.en-322.svc.cluster.local:4000/eureka/,http://eureka-server-1.eureka-server.en-322.svc.cluster.local:4000/eureka/,http://eureka-server-2.eureka-server.en-322.svc.cluster.local:4000/eureka/
      defaultZone : http://eureka-server.en-322.svc.cluster.local:4000/eureka/


management :
  security :
    enabled : false
    